# .yml client configuration file
---
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/cloud-server-eureka/

words: I, You, He, She, It

server:
  port: ${PORT:${SERVER_PORT:0}}
